import { NextResponse } from "next/server"
import { getDatabase } from "@/lib/mongodb"
import type { Lesson } from "@/types"
import { Collection, OptionalId } from "mongodb"

// Sample lessons data
const sampleLessons: Lesson[] = [
  {
    title: "The Kingdom of Aksum",
    content: [
      "The",
      "Kingdom",
      "of",
      "Aksum",
      "was",
      "a",
      "powerful",
      "ancient",
      "civilization",
      "that",
      "flourished",
      "in",
      "northern",
      "Ethiopia",
      "from",
      "approximately",
      "100",
      "to",
      "960",
      "CE.",
      "Known",
      "for",
      "its",
      "impressive",
      "obelisks",
      "and",
      "advanced",
      "trade",
      "networks,",
      "Aksum",
      "was",
      "one",
      "of",
      "the",
      "great",
      "powers",
      "of",
      "the",
      "ancient",
      "world.",
      "The",
      "kingdom",
      "controlled",
      "important",
      "trade",
      "routes",
      "between",
      "the",
      "Roman",
      "Empire",
      "and",
      "Ancient",
      "India,",
      "making",
      "it",
      "incredibly",
      "wealthy",
      "and",
      "influential.",
    ],
    language: "english",
    tags: ["history", "ancient", "kingdom", "trade"],
    difficulty: "beginner",
    audioUrl: "/assets/audio/aksum-ambient.mp3",
    createdAt: new Date(),
  },
  {
    title: "Emperor Haile Selassie",
    content: [
      "Emperor",
      "Haile",
      "Selassie",
      "I",
      "was",
      "the",
      "last",
      "emperor",
      "of",
      "Ethiopia,",
      "ruling",
      "from",
      "1930",
      "to",
      "1974.",
      "Born",
      "as",
      "Tafari",
      "Makonnen,",
      "he",
      "became",
      "a",
      "symbol",
      "of",
      "African",
      "independence",
      "and",
      "resistance",
      "against",
      "colonialism.",
      "His",
      "speech",
      "to",
      "the",
      "League",
      "of",
      "Nations",
      "in",
      "1936,",
      "following",
      "the",
      "Italian",
      "invasion",
      "of",
      "Ethiopia,",
      "remains",
      "one",
      "of",
      "the",
      "most",
      "powerful",
      "addresses",
      "in",
      "diplomatic",
      "history.",
      "He",
      "warned",
      "the",
      "world",
      "about",
      "the",
      "dangers",
      "of",
      "fascism",
      "and",
      "called",
      "for",
      "collective",
      "security.",
    ],
    language: "english",
    tags: ["emperor", "modern", "resistance", "diplomacy"],
    difficulty: "intermediate",
    audioUrl: "/assets/audio/selassie-ambient.mp3",
    createdAt: new Date(),
  },
  {
    title: "The Battle of Adwa",
    content: [
      "The",
      "Battle",
      "of",
      "Adwa",
      "on",
      "March",
      "1,",
      "1896,",
      "was",
      "a",
      "decisive",
      "victory",
      "for",
      "Ethiopian",
      "forces",
      "over",
      "the",
      "Italian",
      "army.",
      "Led",
      "by",
      "Emperor",
      "Menelik",
      "II",
      "and",
      "Empress",
      "Taytu",
      "Betul,",
      "Ethiopian",
      "warriors",
      "defeated",
      "a",
      "well-equipped",
      "European",
      "colonial",
      "force.",
      "This",
      "victory",
      "ensured",
      "Ethiopia's",
      "independence",
      "and",
      "made",
      "it",
      "the",
      "only",
      "African",
      "nation",
      "to",
      "successfully",
      "resist",
      "European",
      "colonization",
      "in",
      "the",
      "19th",
      "century.",
      "The",
      "battle",
      "became",
      "a",
      "symbol",
      "of",
      "African",
      "resistance",
      "and",
      "pride",
      "throughout",
      "the",
      "continent.",
    ],
    language: "english",
    tags: ["battle", "independence", "resistance", "victory"],
    difficulty: "advanced",
    audioUrl: "/assets/audio/adwa-ambient.mp3",
    createdAt: new Date(),
  },
  {
    title: "Lucy - Dinkinesh",
    content: [
      "Lucy,",
      "known",
      "as",
      "Dinkinesh",
      "in",
      "Amharic,",
      "is",
      "one",
      "of",
      "the",
      "most",
      "famous",
      "early",
      "human",
      "ancestors",
      "ever",
      "discovered.",
      "Found",
      "in",
      "Ethiopia's",
      "Afar",
      "region",
      "in",
      "1974",
      "by",
      "paleontologist",
      "Donald",
      "Johanson,",
      "this",
      "3.2",
      "million",
      "year",
      "old",
      "fossil",
      "revolutionized",
      "our",
      "understanding",
      "of",
      "human",
      "evolution.",
      "Lucy",
      "belonged",
      "to",
      "the",
      "species",
      "Australopithecus",
      "afarensis",
      "and",
      "walked",
      "upright,",
      "making",
      "her",
      "a",
      "crucial",
      "link",
      "in",
      "the",
      "human",
      "evolutionary",
      "chain.",
      "Ethiopia",
      "is",
      "truly",
      "the",
      "cradle",
      "of",
      "humanity.",
    ],
    language: "english",
    tags: ["paleontology", "evolution", "discovery", "science"],
    difficulty: "intermediate",
    audioUrl: "/assets/audio/lucy-ambient.mp3",
    createdAt: new Date(),
  },
]

export async function GET() {
  try {
    const db = await getDatabase()
    const lessonsCollection = db.collection<Lesson>("lessons")

    // Check if lessons already exist
    const existingLessons = await lessonsCollection.find({}).toArray()

    if (existingLessons.length === 0) {
      await lessonsCollection.insertMany(sampleLessons as OptionalId<Lesson>[])
    }

    const lessons = await lessonsCollection.find({}).sort({ createdAt: -1 }).toArray()

    return NextResponse.json(lessons)
  } catch (error) {
    console.error("Error fetching lessons:", error)
    return NextResponse.json({ error: "Failed to fetch lessons" }, { status: 500 })
  }
}
